### ISSUE TITLE
XML RPC cannot marshal non

### ISSUE THREAD

**Issue by bodtx** [Chralu/gandyn#21]
i my key and conf seems correct
I have this error

`Traceback (most recent call last):
  File "/usr/local/bin/gandyn.py", line 161, in <module>
    main(sys.argv, globals(), locals())
  File "/usr/local/bin/gandyn.py", line 143, in main
    previous_ip_address = gandi_updater.get_record_value()
  File "/usr/local/bin/gandyn.py", line 53, in get_record_value
    self.record
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1426, in __request
    allow_none=self.__allow_none).encode(self.__encoding, 'xmlcharrefreplace')
  File "/usr/lib/python3.5/xmlrpc/client.py", line 951, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 527, in dump_nil
    raise TypeError("cannot marshal None unless allow_none is enabled")
TypeError: cannot marshal None unless allow_none is enabled
`

**Comment by elmp51** [comment]
I have the same issue.

Thks

**Comment by elmp51** [comment]
Sorry I solved the error.
The zone file on Gandy was not anymore associated to my domain name.
