### ISSUE TITLE
Gandyn does not work anymore

### ISSUE THREAD

**Issue by ignace72** [Chralu/gandyn#23]
Hello
Gandyn does not work anymore, this is the exit of the terminal.
If someone has an idea ?
Thank you
`Traceback (most recent call last):
  File "/usr/bin/gandyn.py", line 161, in <module>
    main(sys.argv, globals(), locals())
  File "/usr/bin/gandyn.py", line 143, in main
    previous_ip_address = gandi_updater.get_record_value()
  File "/usr/bin/gandyn.py", line 53, in get_record_value
    self.record
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1446, in __request
    allow_none=self.__allow_none).encode(self.__encoding, 'xmlcharrefreplace')
  File "/usr/lib/python3.7/xmlrpc/client.py", line 971, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 502, in dumps
    dump(v, write)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 524, in __dump
    f(self, value, write)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 528, in dump_nil
    raise TypeError("cannot marshal None unless allow_none is enabled")
TypeError: cannot marshal None unless allow_none is enabled`

**Comment by arnaudlamy** [comment]
Hi @ignace72 ,

Did you find how to fix it?
